version: '3.4'

services:
  wardrobeonline.webapi:
    container_name: WardrobeWebApi
    image: ${DOCKER_REGISTRY-}wardrobeonlinewebapi
    build:
      context: .
      dockerfile: WardrobeOnline.WebApi/Dockerfile
    networks:
    - internal
    env_file:
     - ./.env