version: '3.4'
# include:
#   - path:    
#     - ../MasterDominaSystem/docker-compose.yml 
#     - ../WardrobeOnline.WebApi/docker-compose.yml
#     - ../ManyEntitiesSender/docker-compose.yml
  
services:
  rabbit:
    container_name: RabbitMQ
    image: rabbitmq:3.10.7-management
    environment:
    - RABBITMQ_DEFAULT_USER=${Broker__RabbitMQ__User} 
    - RABBITMQ_DEFAULT_PASS=${Broker__RabbitMQ__Password}
    ports:
    - 15672:15672
    networks:
    - internal

  kafka:
    container_name: Kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  postgres:
    container_name: PostgreSQL
    image: postgres:latest
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d wardrobe'"]
      interval: "10s"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    networks:
    - internal
    ports:
    - 3000:5432

  redis:
    container_name: RedisServer
    image: redis:7.2.5
    networks:
    - internal
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "10s"

  manyentitiessender:
    container_name: SenderWebApi
    image: ${DOCKER_REGISTRY-}manyentitiessender
    build:
      context: .
      dockerfile: ../ManyEntitiesSender/ManyEnitiesSender/Dockerfile
    networks:
    - internal
    env_file:
    - ./.env
  
  masterdominasystem:
    container_name: MasterDomainSystem
    image: ${DOCKER_REGISTRY-}masterdominasystem
    build:
      context: .
      dockerfile: ../MasterDominaSystem/MasterDominaSystem/Dockerfile
    networks:
    - internal
    env_file:
    - ./.env
    depends_on:
    - postgres
    - rabbit

  wardrobeonline.webapi:
    container_name: WardrobeWebApi
    image: ${DOCKER_REGISTRY-}wardrobeonlinewebapi
    build:
      context: .
      dockerfile: ../WardrobeOnline/WardrobeOnline.WebApi/Dockerfile
    networks:
    - internal
    env_file:
     - ./.env

networks:
  internal: {}

volumes:
  db-data: {}