version: '3.4'

services:
  manyentitiessender:
    container_name: WebApi
    image: ${DOCKER_REGISTRY-}manyentitiessender
    build:
      context: .
      dockerfile: ManyEnitiesSender/Dockerfile
    networks:
    - internal
    env_file:
    - ./.env


